name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./STUDENT_ATTENDENCE-main/stu-attendence --file ./STUDENT_ATTENDENCE-main/stu-attendence/Dockerfile --tag my-image-name:latest

